while True:
	print("Hola mundo!")
	print("Hola soy Fran")
	print("Holasoyivan:D")
	print("hola soy oscar")
	print("Hola a todos, soy Naza")
    print("Hola, soy Mateo")
    print("Hola, soy Javiercillo")
	print("Hola buenas soy ivan")
	print("Hola, soy Alejandro")
	print("Hola soy Pablo!")
	print("Hola, soy Leonard")
	print("Hola, soy ÓscarS")